name: ETF Analysis

on:
  schedule:
    # 8:00 AM IST → 2:30 UTC
    - cron: "30 2 * * *"
    # 5:00 PM IST → 11:30 UTC
    - cron: "30 11 * * *"

  workflow_dispatch:  # allows manual run

jobs:
  run-etf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETF script
        run: |
          python etf_rotation.py